Take the port into account when handling requests, so that example.com and example.com:3000 aren't the same.
Exception: http://example.com/ is identical to http://example.com:80/, and https://example.com/ is identical to https://example.com:443/.